config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "rooms#chatroom"
  get 'blankroom',  to: 'rooms#blankroom'
  resources :users, only: :show
  resources :rooms do
    resources :todos
    resources :schedules
    resources :messages
    member do
      get 'mypage',     to: 'rooms#mypage'
      get 'chatroom',   to: 'rooms#chatroom'
      get 'roomsearch', to: 'rooms#roomsearch'
      get 'todo',       to: 'rooms#todo'
      get 'schedule',   to: 'rooms#schedule'
      get 'gallery',    to: 'rooms#gallery'
      post 'join',      to: 'rooms#join'
      get 'exit',       to: 'rooms#exit'
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :room

  with_options presence: true do
    validates :date
    validates :detail
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :params_current_room

  def new
    @schedule = Schedule.new
  end

  def create
    @room = RoomUser.find_by(user_id: current_user.id)
    @schedule = Schedule.new(params.require(:schedule).permit(:date, :detail).merge(room_id: @room.room_id,))
    if @schedule.valid?
      @schedule.save
      redirect_to schedule_room_path(current_user.id)
    else
      render 'new'
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    @schedule.update(params.require(:schedule).permit(:date, :detail))
    redirect_to schedule_room_path(@room.id)
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedule_room_path(@room.id)
  end

  private

  def params_current_room
    @roomuser = RoomUser.find_by(user_id: current_user.id)
    @room = Room.find(@roomuser.room_id)
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.erb
<div class="body">
  <%= render partial: 'rooms/left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">EditSchedule</div>
      </div>
      <div class="main-area">
        <%= form_with model: [@room, @schedule], id: 'addschedule-form', class: 'addshedule-form', local: true do |f| %>

          <%= render 'shared/error_messages', model: f.object %>

          <%= f.label :date, class:"field-label"%><br />
          <%= f.date_select :date, with_css_classes:"date-select" %><br />

          <%= f.label :detail, class:"field-label"%><br />
          <%= f.text_area :detail, class:"field-input f overview", autofocus: true %><br />

          <%= f.submit "UpDate", class:"actions" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="body">
  <%= render partial: 'rooms/left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">AddSchedule</div>
      </div>
      <div class="main-area">
        <%= form_with model: [@room, @schedule],url: room_schedules_path(@room.id), id: 'addschedule-form', class: 'addshedule-form', local: true do |f| %>

          <%= render 'shared/error_messages', model: f.object %>

          <%= f.label :date, class:"field-label"%><br />
          <%= f.date_select :date, with_css_classes:"date-select" %><br />

          <%= f.label :detail, class:"field-label"%><br />
          <%= f.text_area :detail, class:"field-input f overview", autofocus: true %><br />

          <%= f.submit "Add", class:"actions" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/schedules/show.html.erb
<div class="body">
  <%= render partial: 'rooms/left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">ScheduleDetail</div>
        <div class="main-head-btns">
          <div class="main-head-btn">
            <%= link_to "Schedule Edit", edit_room_schedule_path %>
          </div>
          <div class="main-head-btn">
            <%= link_to "Schedule Delete", room_schedule_path, method: :delete %>
          </div>
        </div>
      </div>
      <div class="main-area">
        <div class="detail-label">Title</div>
        <div class="title"> <%= @schedule.date %></div>
        <div class="detail-label">Details</div>
        <div class="schedule-show-detail"><%= @schedule.detail %></div>
      </div>
    </div>
  </div>
</div>