config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "rooms#chatroom"
  get 'blankroom',  to: 'rooms#blankroom'
  resources :users, only: :show
  resources :rooms do
    resources :todos
    resources :schedules
    resources :messages
    member do
      get 'mypage',     to: 'rooms#mypage'
      get 'chatroom',   to: 'rooms#chatroom'
      get 'roomsearch', to: 'rooms#roomsearch'
      get 'todo',       to: 'rooms#todo'
      get 'schedule',   to: 'rooms#schedule'
      get 'gallery',    to: 'rooms#gallery'
      post 'join',      to: 'rooms#join'
      get 'exit',       to: 'rooms#exit'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :schedules, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :overview
    validates :leader
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :params_current_room

  def new
    @room = Room.new
  end

  def create
      @room = Room.new(room_params)
    if @room.valid?
      @room.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
  end

  def update
    if @room.update(room_update_params)
      redirect_to chatroom_room_path
    else
      render 'edit'
    end
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  def exit
    @roomuser = RoomUser.find_by(user_id: current_user.id)
    @roomuser.destroy
    redirect_to root_path
  end

  def join
    @room = Room.find(params[:id])
    if RoomUser.create(room_id: @room.id, user_id: current_user.id)
      redirect_to chatroom_room_path
    else
      redirect_to room_path
    end
  end

  def mypage
    @user = User.find(current_user.id)
  end

  def chatroom
    if RoomUser.find_by(user_id: current_user.id).present?
      @message = Message.new
      @roomuser = RoomUser.find_by(user_id: current_user.id)
      @room = Room.find(@roomuser.room_id)
      @messages = @room.messages.includes(:user)
    else
      redirect_to blankroom_path
    end
  end

  def blankroom
  end

  def roomsearch
    @rooms = Room.all
  end

  def todo
  end

  def schedule
    if RoomUser.find_by(user_id: current_user.id).present?
      @roomuser = RoomUser.find_by(user_id: current_user.id)
      @room = Room.find(@roomuser.room_id)
      @schedules = @room.schedules.order(:date)
    else
      redirect_to blankroom_room_path
    end
  end

  def gallery
  end

  private

  def room_params
    params.require(:room).permit(:title, :category, :capacity, :overview, :budget, :details, user_ids: []).merge(leader: current_user.id)
  end

  def room_update_params
    params.require(:room).permit(:title, :category, :capacity, :overview, :budget, :details)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_left_navigation.html.erb
<div class="left-navigation">
  <div class="nav-logo">Adventure</div>
  <ul class="nav">
    <li><%= link_to "RoomSearch", roomsearch_room_path(current_user), class:"nav-list" %></li>
    <li><%= link_to "MyPage", mypage_room_path(current_user), class:"nav-list" %></li>
    <% if RoomUser.find_by(user_id: current_user.id).present? %>
      <li><%= link_to "ChatRoom", chatroom_room_path(current_user), class:"nav-list" %></li>
      <li><%= link_to "Schedule", schedule_room_path(room.id), class:"nav-list" %></li>
      <!-- <li><%= link_to "Gallery", gallery_room_path(room.id), class:"nav-list" %></li> -->
    <% else %>
      <li><%= link_to "ChatRoom", blankroom_path, class:"nav-list" %></li>
      <li><%= link_to "Schedule", blankroom_path, class:"nav-list" %></li>
    <% end %>
    
  </ul>
  <div class="logout"><%= link_to "LogOut", destroy_user_session_path, method: :delete %></div>
</div>

app/views/rooms/_message.html.erb
<div class="message" id='messages' >
  <div class="left-message" id="left-message">
    <% if message.user.icon.attached? %>
      <%= image_tag message.user.icon.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0"), class:"message-user-icon", id:"message-user-icon" %>
    <% else %>
      <%= image_tag "user-icon.png", class:"message-user-icon", id:"message-default-icon" %>
    <% end %><br />
    <div class="message-user">
      <div class="message-name">
        <%= link_to  message.user.name, user_path(message.user_id) %>
      </div><br />
      <div class="message-content">
        <%= message.content %> 
      </div>
    </div>
  </div>
  <%#= image_tag message.image.variant(resize: '200x200'), class: 'message-image' if message.image.attached? %>
  <div class="right-message">
    <div class="message-date">
      <%= l message.created_at %>
    </div> 
  </div>
</div>

app/views/rooms/blankroom.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
      </div>
      <div class='alert'>Please join the room</div>
      </div>
  </div>
</div>

app/views/rooms/chatroom.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="chatmain">
      <div class="main-head">
        <div class="main-index">ChatRoom</div>
        <div class="main-head-btns">
        <div class="main-head-btn" ><%= link_to "Edit Room", edit_room_path(@room.id) %></div>
        <% if @room.leader == current_user.id %>
          <div class="main-head-btn" ><%= link_to "Delete Room", room_path(@room.id), method: :delete %></div>
        <% else %>
          <div class="main-head-btn" ><%= link_to "Exit Room", exit_room_path(@room.id) %></div>
        <% end %>
        </div>
      </div>
      <div class="main-area" id="scroll-message">
        <% @messages.each do |message| %>
        <div id="message-container">
          <%= render partial: 'message',locals: { message: message }%>
        </div>
        <% end %>
        <div id="add-message">
        </div>
      </div>
    </div>
    <%= form_with model: [@room, @message], class:"message-form" do |f| %>
      <%= f.text_field :content, class:"message-field", placeholder:"Message", autofocus: true %>
      <!-- <label class="input-image">
      <%= f.file_field :image, class: "upload-file" %>
      </label> -->
      <%= f.submit "", class:"send", id:"send" %>
    <% end %>
  </div>
</div>

app/views/rooms/edit.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">EditRoom</div>
      </div>
      <%= form_with model: @room, id: 'addroom-form', class: 'addroom-form', local: true do |f| %>

        <div class="form-left">
        <%= render 'shared/error_messages', model: f.object %>
        <%= f.label :title, class:"field-label"%><br />
        <%= f.text_field :title, class:"field-input f", autofocus: true %><br />

        <%= f.label :overview, class:"field-label" %><br />
        <%= f.text_area :overview, class:"field-input f overview" %><br />

        <%= f.label :budget, class:"field-label" %><br />
        <%= f.text_field :budget, class:"field-input f" %><br />
          </div>
          <div class="form-right">
        <%= f.label :details, class:"field-label" %><br />
        <%= f.text_area :details, class:"field-input f details" %><br />

        <%= f.submit "Update", class:"actions" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/gallery.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
  </div>
</div>

app/views/rooms/mypage.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">MyPage</div>
        <div class="main-head-btn" ><%= link_to "Edit User", edit_user_registration_path %></div>
      </div>
      <div class="mypage-content">
      <% if @user.icon.attached? %>
        <%= image_tag @user.icon.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0"), class: "user-icon" %>
      <% else %>
        <%= image_tag "user-icon.png", class:"user-icon" %>
      <% end %>
          <div class="name">Name:  <%= @user.name %></div>
        <div class="profile-area">
          <div class="profile-label">Profile:</div><br />
          <div class="profile"><%= @user.profile %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">AddRoom</div>
      </div>
      <div class="main-area">
      <%= form_with model: @room, id: 'addroom-form', class: 'addroom-form', local: true do |f| %>

        <div class="form-left">
        <%= render 'shared/error_messages', model: f.object %>
          <%= f.label :title, class:"field-label"%><br />
          <%= f.text_field :title, class:"field-input f", autofocus: true %><br />

          <%= f.label :budget, class:"field-label" %><br />
          <%= f.text_field :budget, class:"field-input f" %><br />

          <%= f.label :overview, class:"field-label" %><br />
          <%= f.text_area :overview, class:"field-input f overview" %><br />
        </div>
        <div class="form-right">
          <%= f.label :details, class:"field-label" %><br />
          <%= f.text_area :details, class:"field-input f details" %><br />
          <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
          <%= f.submit "Add", class:"actions" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/roomsearch.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">RoomSearch</div>
        <% if RoomUser.find_by(user_id: current_user.id).blank? %>
          <div class="main-head-btn" ><%= link_to "Add Room", new_room_path %></div>
        <% end %>
      </div>
      <div class="room-list">
        <% @rooms.each do |room| %>
          <div class="room">
            <%= link_to room.title, room_path(room.id), class:"room-title"%>
            <div class="room-overview"><%= room.overview %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/schedule.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">Schedule</div>
        <div class="main-head-btn" ><%= link_to "Add Schedule", new_room_schedule_path(@room) %></div>
      </div>
      <div class="main-area">
        <% @schedules.each do |schedules| %>
          <div class="schedule-container">
            <div class="schedule-date"><%= link_to schedules.date, room_schedule_path(schedules.room_id, schedules.id) %></div>
            <div class="schedule-detail"><%= schedules.detail %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">RoomDetail</div>
      </div>
      <div class="detail">
        <div class="left-content">
          <div class="detail-label">Title</div>
          <div class="title"> <%= @room.title %></div>

          <div class="detail-label">Budget</div>
          <div class="budget"> <%= @room.budget %></div>

          <div class="detail-label">Overview</div>
          <div class="overview"> <%= @room.overview %></div>
        </div>
        <div class="right-content">
          <div class="detail-label">Details</div>
          <div class="details"> <%= @room.details %></div>
          <%= form_with model: @room, url: join_room_path, method: :post, local: true do |f| %>
          <% if RoomUser.find_by(user_id: current_user.id).blank? %>
            <%= f.submit "Join", class:"actions" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/todo.html.erb
<div class="body">
  <%= render partial: 'left_navigation', locals: { room: @room }%>
  <div class="content">
    <div class="contents-bg"></div>
    <div class="main">
      <div class="main-head">
        <div class="main-index">Todo</div>
        <div class="main-head-btn" ><%= link_to "Add Todo", new_room_todo_path(@todo) %></div>
      </div>
    </div>
  </div>
</div>